# Configuration for CloudCannon and Jekyll

# Site Metadata
title: "Your Site Title"
description: "A short description of your site."
url: "https://your-site-url.com"

# CloudCannon Settings
cloudcannon:
  uploads: uploads                   # Directory for uploaded files
  collections_config:
    # Define collections (adjust as per your project needs)
    pages:
      path: _pages                    # If you store pages in _pages folder
      output: true                     # Pages should be output as part of the build
      auto_discovered: true            # Auto-discovery of pages collection
    posts:
      path: _posts                    # Blog posts directory
      output: true                     # Posts should be output in final site
      auto_discovered: true            # Auto-discovery of posts collection
  _inputs: []                          # Inputs section (define if needed)
  _snippets: []                        # Snippets section (define if needed)
  _enabled_editors:
    - markdown
    - html
    - data                           # Enable these editors for CloudCannon

# Jekyll Settings
source: ./                              # Set root folder as source for clarity
destination: ./_site                    # Jekyll's default output folder

# Base URL
baseurl: ""                             # Use empty if the site is hosted at the root

# Markdown & Layout
markdown: kramdown                      # Jekyll default markdown processor
theme: "jekyll-theme-slate"             # Choose your Jekyll theme

# Collections (Optional)
collections:
  # Example collection: 'projects'
  projects:
    output: true
    permalink: /projects/:title/        # Custom URL structure for projects

# URL Configurations
permalink: /:year/:month/:day/:title/   # Permalink structure for posts

# Exclude files and folders
exclude:
  - "node_modules/"
  - "Gemfile.lock"
  - "README.md"
  - "docs/*"

# Plugins (If any plugins used)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build Settings
sass:
  style: compressed                   # Minified CSS for production

# CloudCannon-specific directories and settings
directories:
  assets: _assets                       # Assets folder for CloudCannon (e.g., images, CSS)
  data: _data                           # Data folder for Jekyll (_data contains YAML files)
  pages: _pages                         # Pages directory for easy editing

# Miscellaneous Settings
env:
  JEKYLL_ENV: production                # Default environment for production build
  CI: false                             # Disable continuous integration notifications

# Additional CloudCannon Settings (optional, but helps with the workflow)
cloudcannon:
  theme: default                        # Optional CloudCannon theme if needed
  ui:
    toolbar: true                       # Show CloudCannon's toolbar for editors
