title: Fizzy Affairs
description: Spritz van for events & weddings
baseurl: ''
url: ''
collections:
  pages:
    output: true
    permalink: /:path/
    _editable: true
_uploads_dir: uploads
_data_dir: _data
plugins:
  - jekyll-sitemap
markdown: kramdown
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
