seo:
  site_name: Fizzy Affairs
  title: Prosseco Van
  description: >-
    Celebrate in style with Fizzy Affairs – a mobile bar service based in
    Antibes offering organic Prosecco, craft cocktails, and customizable
    packages for weddings, private parties, and events. Let us bring the sparkle
    to your special day!
  keywords: >-
    Mobile bar service Antibes, Organic Prosecco service, Customizable event
    packages, Wedding mobile bar, Private party bar service, Corporate event
    mobile bar, Cocktail catering French Riviera, Antibes event services,
    Champagne bar Antibes, French Riviera event catering, Premium Prosecco for
    events, Prosecco and cocktail service, Antibes wedding bar hire, Event drink
    catering Antibes, Antibes mobile Prosecco bar, Luxury bar service Antibes,
    Wedding cocktail bar French Riviera, Sparkling wine catering, Antibes event
    planning, Private celebration drinks service.
  social_image:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: '#1d1918'
  light-text_color: '#f5f1ed'
  featured-text-white_color: '#ffffff'
  bg-dark_color: '#493628'
  bg-light_color: '#ffffff'
  bg-beige_color: '#f5f1ed'
